### ISSUE TITLE
passing arguments to flow

### ISSUE THREAD

**Issue by bj00rn** [jedwards1211/flow-watch#13]
Hi, thanks for the great work!

Is it possible to pass arguments to flow binary? 
Would be nice to be able to pass options such as `--show-all-errors`

**Comment by jedwards1211** [comment]
Okay, fixed in 1.1.5!  All arguments that aren't recognized nodemon options will be passed through to flow

**Comment by bj00rn** [comment]
@jedwards1211 thanks for the just-in-time delivery!

works as expected
