### ISSUE TITLE
Babel compatibility?

### ISSUE THREAD

**Issue by elmarsto** [jedwards1211/flow-watch#6]
vanilla Flow works well with Babel (when used with no arguments). But flow-watch (on Ubuntu Linux 16.04.1, Node v8.x) appears to to bypass Babel. Am I flow-watching wrong?

**Comment by jedwards1211** [comment]
Oh gosh, sorry for the huge delay in responding to this.

I'm not sure what to think, since `flow-watch` is just spawning `flow` under the hood.  You're seeing errors when using `flow-watch` but not `flow` I take it?

**Comment by jedwards1211** [comment]
I'm going to close this, but ping me if you still have a question about it.  Sorry again that I missed this issue at first.
