### ISSUE TITLE
Use cross-spawn to support windows

### ISSUE THREAD

**Issue by pietrofxq** [jedwards1211/flow-watch#7]
This script isn't working in windows because `spawn` doesn't work properly. [cross-spawn](https://github.com/moxystudio/node-cross-spawn) should be used to enable support for Windows.

**Comment by jedwards1211** [comment]
Yup, unfortunately.  I just added a commit to use `cross-spawn`, the fix should be released once the CI build passes!

**Comment by pietrofxq** [comment]
Actually this wasn't the issue for me. I'm still getting this:

```
Error: Cannot find module 'C:\Users\Pietro Coelho\Desktop\Projetos\flow-watch\"C:\Users\Pietro'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:453:25)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
```

I couldn't find which module is throwing the error, but looks like the problem is with spaces in the absolute file path.
